# Generated by Django 3.2.18 on 2023-05-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='is_user',
            new_name='is_registered_already',
        ),
    ]
