# Generated by Django 3.2.18 on 2023-05-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230514_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='{{ MEDIA_URL }}noimage.png', upload_to=''),
        ),
    ]
