# Generated by Django 3.2.18 on 2023-05-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available',
            field=models.DateField(blank=True, null=True),
        ),
    ]
