# Generated by Django 3.2.18 on 2023-05-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='available',
        ),
        migrations.AddField(
            model_name='item',
            name='availableDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
